### ISSUE TITLE
falsches Wort

### ISSUE THREAD

**Issue by vsaase** [dys2p/wordlists-de#3]
https://github.com/dys2p/wordlists-de/blob/5eba8aecb872a7dc390458eaa4a4ebdbcf88b70d/de-2048-v1.txt#L572

das war wohl falsch :)

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Vielen Dank @vsaase das false Wort wurde [ersetzt](https://github.com/dys2p/wordlists-de/commit/f0a1b71f699222c4f7b3a2414245f10cd332bb71).
